---
# tasks file for deluge

- name: Add Deluge PPA
  apt_repository: repo=ppa:deluge-team/ppa state=present

- name: Install Deluge Daemon
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - deluged
    - deluge-web
    - deluge-console

- name: Make sure deluge group is available
  group: name={{ deluged_user }} state=present

- name: Make sure deluge user is available
  user: name={{ deluged_user }} group={{ deluged_user }} state=present

- name: Create Deluge Daemon Directory
  file: path={{ item }} state=directory owner={{ deluged_user }} group={{ deluged_user }} mode=0755
  with_items:
    - "{{ deluged_path }}"
    - "{{ deluged_path }}/config"

- name: Update Deluge Daemon init script
  template: src=etc_init.d_deluged dest=/etc/init.d/deluged owner=root group=root mode=0755

- name: Update Deluge Web init script
  template: src=etc_init.d_deluge-web dest=/etc/init.d/deluge-web owner=root group=root mode=0755

- name: Update Deluge Daemon default config
  template: src=etc_default_deluged dest=/etc/default/deluged owner=root group=root

- name: Update Deluged core.conf
  template: src=core.conf.j2 dest={{ deluged_path }}/config/core.conf owner={{ deluged_user }} group={{ deluged_user }} mode=0640
  register: deluged_core_update

- name: Stop deluged daemon before reapplying core.conf update
  service: name=deluged state=stopped
  when: deluged_core_update.changed

- name: Reapply deluged core.conf update
  template: src=core.conf.j2 dest={{ deluged_path }}/config/core.conf owner={{ deluged_user }} group={{ deluged_user }} mode=0640
  when: deluged_core_update.changed

- name: Create Deluge downloads folders
  file: path={{ item }} state=directory owner={{ deluged_user }} mode=0775
  with_items:
    - "{{ downloads_path }}"
    - "{{ deluged_incomplete }}"

- name: Create process folder for nzbtomedia processing
  file: path={{ item }} state=directory owner={{ deluged_user }} mode=0775
  with_items:
    - "{{ process_path }}"

- name: Configure Label plugin
  template: src=label.conf.j2 dest="{{ deluged_path }}/config/label.conf" owner={{ deluged_user }} group={{ deluged_user }} mode=0640

- name: Update Execute plugin config
  template: src=execute.conf.j2 dest="{{ deluged_path }}/config/execute.conf" owner={{ deluged_user }} group={{ deluged_user }} mode=0640

- name: Update Deluge credentials
  lineinfile: dest={{ deluged_path }}/config/auth regexp='^localclient' line='localclient:{{ deluged_localclient_password }}:10' owner={{ deluged_user }} group={{ deluged_user }} mode=0600 create=yes

- name: Make sure Deluge Daemon is running and enabled on boot
  service: name=deluged state=started enabled=yes

- name: Make sure Deluge Web is running and enabled on boot
  service: name=deluge-web state=started enabled=yes
