---
- hosts: htpc-server
  sudo: True

  vars:

    ## Most commonly modifiable values.
    ## For a full list of tunable parameters check each role README.md in roles/role-name/README.md  

    # xbmc-client role variables
    # --------------------------
    
    xbmc_repo: 'ppa:team-xbmc/ppa'        # XBMC Ubuntu ppa.
    media_path: /mnt/media                # Location of xbmc media folders.
    xbmc_user_name: xbmc                  # User that will run XBMC
    xbmc_user_password: xbmc              # User's Password
    xbmc_enable_ubuntu_desktop: True      # Start XBMC as part of Ubuntu desktop

    # sabnzbd role variables
    # ----------------------
    
    # newsgroups_servers:
    #   - name: news.example.com
    #     username: foo
    #     password: bar
    #     connections: 20

    # usenet_crawler_api_key: your_personal_usenet_crawler_api_key

    # htpc-manager role variables
    # ---------------------------

    htpc_manager_use_hostnames: True      # If False use IP Addresses.


  # Any role can be commented out to disable particular function.
  roles:
    - role: xbmc-client
    - role: xbmc-mysql
    - role: xbmc-nas
    - role: deluge
    - role: sabnzbd
    - role: sickbeard
    - role: couchpotato
    - role: htpc-manager
    - role: tvheadend
