---
- hosts: htpc-server
  sudo: True

  vars:
    htpc_manager_use_hostnames: True

  roles:
    - role: xbmc-client
    - role: xbmc-mysql
    - role: xbmc-nas
    # - role: deluge
    - role: sabnzbd
    - role: sickbeard
    - role: couchpotato
    - role: htpc-manager
