- src: https://github.com/GR360RY/ansible-role-htpc-common.git
  name: GR360RY.htpc-common
  path: roles/

- src: https://github.com/GR360RY/ansible-role-kodi-client.git
  name: GR360RY.kodi-client
  path: roles/

- src: https://github.com/GR360RY/ansible-role-kodi-mysql.git
  name: GR360RY.kodi-mysql
  path: roles/

- src: https://github.com/GR360RY/ansible-role-htpc-nas.git
  name: GR360RY.htpc-nas
  path: roles/

- src: https://github.com/GR360RY/ansible-role-nzbtomedia.git
  name: GR360RY.nzbtomedia
  path: roles/

- src: https://github.com/GR360RY/ansible-role-deluge.git
  name: GR360RY.deluge
  path: roles/

- src: https://github.com/GR360RY/ansible-role-sickrage.git
  name: GR360RY.sickrage
  path: roles/

- src: https://github.com/GR360RY/ansible-role-htpc-manager.git
  name: GR360RY.htpc-manager
  path: roles/