---
# defaults file for sabnzbd
sabnzbd_enabled: True

sabnzbd_user: root

sabnzbd_port: 9000
sab_apikey: c48afc846972e295826bb05d2e84dd59

usenet_crawler_api_key: 9d9af7ab6548948fcdc2db864ecd2588

# Default download locations:
media_path: /mnt/media
downloads_path: "{{ media_path }}/downloads"
sabnzbd_incomplete: "{{ downloads_path }}/incomplete/sabnzbd"

sabnzbd_host: "{{ ansible_default_ipv4.address }}"