---
# tasks file for xbmc-nas

- name: Install NFS Server
  apt: name=nfs-kernel-server state=installed update_cache=yes cache_valid_time=3600

- name: Define NFS shares in /etc/exports
  lineinfile: dest=/etc/exports regexp='^{{ media_path }}' line='{{ media_path }} *(ro,insecure)'
  notify:
    - update nfs exports

- name: Make sure media path is created
  file: path={{ media_path }} state=directory owner={{ htpc_username }} group={{ htpc_username }} mode=0755

- name: Make sure NFS server is started on boot
  service: name=nfs-kernel-server state=started enabled=yes

- name: Install SAMBA server
  apt: name=samba state=installed update_cache=yes cache_valid_time=3600

- name: Update SAMBA configuration
  template: src=smb.conf dest=/etc/samba/smb.conf owner=root group=root
  notify:
    - create samba users
    - restart samba

- name: Make sure SAMBA server is started on boot
  service: name=samba state=started enabled=yes
