---
# handlers file for htpc-nas

- name: update nfs exports
  command: /usr/sbin/exportfs -a

- name: create samba users
  sudo: yes
  shell: (echo "{{ htpc_user_password }}"; echo "{{ htpc_user_password }}") | smbpasswd -s -a {{ htpc_username }}

- name: restart samba
  service: name={{ item }} state=restarted
  with_items:
    - nmbd
    - smbd
