---
# tasks file for couchpotato

- name: Install Requirements
  apt: pkg={{ item }} state=installed
  with_items:
    - python-cheetah
    - git

- name: Get Couchpotato Code from GitHub
  git: repo={{ couchpotato_repo }} dest={{ couchpotato_path }} version={{ couchpotato_version }}

- name: Make sure Couchpotato directory has correct ownership
  file: path={{ couchpotato_path }} owner={{ couchpotato_user }} group={{ couchpotato_user }} recurse=yes

- name: Update Couchpotato init.d script
  template: src=init.{{ ansible_os_family }} dest=/etc/init.d/{{ couchpotato_init_script }} owner=root group=root mode=0755

- name: Update Couchpotato Daemon configuration
  template: src=etc_default_couchpotato dest=/etc/default/couchpotato owner=root group=root mode=0644

- name: Create CouchPotato database and settings directory
  file: path=/var/couchpotato state=directory owner={{ couchpotato_user }} group=root mode=0755

- name: Run Couchpotato once to generate config files
  service: name={{ couchpotato_init_script }} state=started pattern='/usr/bin/python CouchPotato.py'

- name: Make sure Couchpotato is stopped before modifications
  service: name={{ couchpotato_init_script }} state=stopped pattern='/usr/bin/python CouchPotato.py'

- name: Update CouchPotato configuration
  template: src=var_couchpotato_settings.conf.j2 dest=/var/couchpotato/settings.conf owner={{ couchpotato_user }} group={{ couchpotato_user }}

- name: Upload CouchPotato Database
  copy: src=couchpotato.db dest=/var/couchpotato/couchpotato.db owner={{ couchpotato_user }} group={{ couchpotato_user }}

- name: Create CouchPotato Media folders
  file: path={{ item }} state=directory recurse=yes owner={{ couchpotato_user }} group={{ couchpotato_user }} mode=0775
  with_items:
    - "{{ media_path }}"
    - "{{ media_path }}/{{ movies_folder }}"

- name: Start Couchpotato and make sure it starts on boot
  service: name={{ couchpotato_init_script }} state=started pattern='/usr/bin/python CouchPotato.py' enabled=yes
